
import { GoogleGenAI, Modality } from "@google/genai";
import { AspectRatio } from '../types';

if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export async function generateWithImagen(prompt: string, numberOfImages: number, aspectRatio: AspectRatio): Promise<string[]> {
    try {
        const response = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt,
            config: {
                numberOfImages,
                aspectRatio,
                outputMimeType: 'image/png',
            },
        });
        
        if (!response.generatedImages || response.generatedImages.length === 0) {
            throw new Error("No images were generated by Imagen.");
        }

        return response.generatedImages.map(img => `data:image/png;base64,${img.image.imageBytes}`);
    } catch (error) {
        console.error("Error generating with Imagen:", error);
        throw new Error("Failed to generate images with Imagen. Please check your prompt or API key.");
    }
}


export async function generateWithNanoBanana(prompt: string): Promise<string[]> {
    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: {
                parts: [{ text: prompt }],
            },
            config: {
                responseModalities: [Modality.IMAGE],
            },
        });

        const imagePart = response.candidates?.[0]?.content?.parts?.find(part => part.inlineData);
        if (imagePart && imagePart.inlineData) {
            const base64ImageBytes: string = imagePart.inlineData.data;
            return [`data:image/png;base64,${base64ImageBytes}`];
        } else {
            throw new Error("No image data found in Nano Banana response.");
        }
    } catch (error) {
        console.error("Error generating with Nano Banana:", error);
        throw new Error("Failed to generate image with Nano Banana. The model may not have been able to fulfill the request.");
    }
}
